### ISSUE TITLE
Get the number of line of front-matter

### ISSUE THREAD

**Issue by wdavidw** [jonschlinkert/gray-matter#108]
I need to report errors and warnings with their associated line number from a markdown file. For example, "Targeted link at line 2 return 301". The problem is that the line number does not take into consideration the number of lines of the front-matter.

My target environnement is a gatsby website using gatsby-transformer-remark which itself uses gray-matter [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/on-node-create.js#L28).

My usecase seems pretty common and I am wondering how other people are handling it, probably outside of gray-matter by parsing the markdown file a second time and extracting the front-matter. It would have been better handled natively inside this package.

There are two ways to handle it. Either by returning the number of line in a propery such as `frontMatterLines` or by return the raw front-matter in a property such as `raw`. With the latest, the user could then simply split the `raw` content to get the number of lines.

Here's an example:

```md
---
title: a title
---

go [here]('https://domain.com/does-no-exists')
```

The above should throw a message like "Targeted link at line 5 return 301" while instead it print "Targeted link at line 2 return 301". I know the line number in the content but I can't add the number of lines of the front-matter.

**Comment by doowb** [comment]
> by return the raw front-matter in a property such as `raw`

Hi @wdavidw , the raw front-matter is returned on a property called `matter`. You can see what the entire object looks like from the [README here](https://github.com/jonschlinkert/gray-matter#returned-object).

You should be able to use that to add the front-matter lines to the error line number.

**Comment by wdavidw** [comment]
Perfect, I didn't saw it. Thank you.
