### ISSUE TITLE
leading newline in body

### ISSUE THREAD

**Issue by ianstormtaylor** [jonschlinkert/gray-matter#11]
Hey, looking to port [Metalsmith](https://metalsmith.io) to gray-matter! 

Ran into a question: it was previously using [front-matter](https://github.com/jxson/front-matter) which stripped a trailing newline after the closing `---`, which seemed to mesh more with how a user "perceives" the frontmatter, if not with the way a computer reads it.

Such that...

```
---
property: true
---
body
```

...would end up being stripped so that it is exactly equal to...

```
body
```

What do you think about supporting that, by swallowing a single newline if one (or more) are present after the closing `---`? Technically not "pure", but matches with users editing the frontmatter more I think?

**Comment by jakwings** [comment]
IMHO, I don't like this feature, and this was one of the reason I abandoned front-matter. The body parser like markdown should be ok with that.

**Comment by jonschlinkert** [comment]
> Hey, looking to port Metalsmith to gray-matter!

Awesome! that's great!

About the newline, sure no problem. Someone else recently mentioned that it should strip the newline. 

> The extra newline can be easily detected after extracting the front matter.

Meaning that implementors could strip the newline? true, but the same point holds for adding a newline.

**Comment by jakwings** [comment]
Adding a newline involes memory rearrangement. I'm not an expert, so that's all.

**Comment by jonschlinkert** [comment]
closing based on #13
