### ISSUE TITLE
parsers

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/gray-matter#12]
@ianstormtaylor, I wanted to get your feedback on this in light of you potentially using this in metalsmith. one of gray-matter's features is that you can pass a parser function on the options, like if you don't want to use js-yaml for instance.  

There are a few parsers currently, for yaml, coffee, javascript, json and toml. I recently had a discussion with @doowb about externalizing/ripping out the parsers and just allowing implementors to just pass in what they want to use - but the vast majority of users will use js-yaml anyway...

Any opinion on this? I could probably go either way - leaning towards ripping them out. if we decide to rip out the parses I can just do it at the same time as the whitespace change, since both would be breaking changes.

**Comment by ianstormtaylor** [comment]
Definitely thought it was sweet when I saw that parsers (and delimiters) were able to be swapped out. 

As for what to bundle, I assume you're talking about keeping the `yaml` parser regardless? Honestly not sure. The `js` and `coffee` ones seem a bit opinionated? But built-in `json`, `yaml`, `toml` seems nice for people. Although I'll only ever use `yaml` like you said. Either just `yaml` or `yaml,json,toml` seems right. I guess someone could ask for an `xml` one, at which point it might be nicer to just have an opinion of only `yaml`.

Side note: I thought regular JSON was "correct" YAML as well, so technically JSON parsing it automatically handled? I guess the only different is the opening and closing `{}`. Even the `json` one might be slightly opinionated in that case, not sure.

**Comment by jonschlinkert** [comment]
> Definitely thought it was sweet when I saw that parsers (and delimiters) were able to be swapped out.

thanks! yeah my inner nerd is resisting taking them out... 

> I assume you're talking about keeping the yaml parser regardless?

yes, definitely. 

> The js and coffee ones seem a bit opinionated? 

noted. I really wasn't sure what to do when I implemented those. it's funny, I've never even used the coffee parser in project (because I forget about it), but I probably should, when I was writing the tests it was pretty fun defining helpers in the front matter and then using them in the same file.  

> But built-in json, yaml, toml seems nice for people.

also noted. that seems like a good mix.

> thought regular JSON was "correct" YAML as well

but I got all excited about being able to let people use JSON lol. 

thanks for the feedback Ian.  @doowb any thoughts?

**Comment by doowb** [comment]
You're already only requiring `js-yaml` if it's used and also allowing passing in a parser function `opts.fn` so I think that should be fine, right?

```js
var myParser = require('my-parser');
var parsed = matter(str, { parser: myParser });
```

**Comment by jonschlinkert** [comment]
closing since gray-matter was refactored. [custom engines](https://github.com/jonschlinkert/gray-matter#optionsengines) are now supported via options (parsing and stringifying), and some sensible defaults are still included.
