### ISSUE TITLE
Not installing with bower

### ISSUE THREAD

**Issue by smkhalsa** [jonschlinkert/gray-matter#14]
When I try to run 
`
bower install gray-matter --save
`
I get the following error:
`
bower extend-shallow#^1.1.2     ENORESTARGET No tag found that was able to satisfy ^1.1.2
`

**Comment by jonschlinkert** [comment]
thanks for the heads up

**Comment by jonschlinkert** [comment]
should be fixed. please reopen if you still have issues.

**Comment by StudioLE** [comment]
I'm also having an issue installing with bower

```
λ bower install gray-matter --save
bower cached        git://github.com/assemble/gray-matter.git#2.0.1
bower validate      2.0.1 against git://github.com/assemble/gray-matter.git#*
bower not-cached    git://github.com/jonschlinkert/extend-shallow.git#^2.0.1
bower resolve       git://github.com/jonschlinkert/extend-shallow.git#^2.0.1
bower ENORESTARGET  No tag found that was able to satisfy ^2.0.1

Additional error details:
Available versions: 2.0.0
```

**Comment by jonschlinkert** [comment]
still not working? hmm, I'll look into it, thanks for reporting.

**Comment by StudioLE** [comment]
Line 15 of [bower.json](https://github.com/jonschlinkert/gray-matter/blob/master/bower.json#L15) specifies extend-shallow#2.0.1 But according to [extend-shallow/releases](https://github.com/jonschlinkert/extend-shallow/releases) the current version is 2.0.0

**Comment by jonschlinkert** [comment]
awesome, thanks for looking into it. I'll get it resolved asap

**Comment by jonschlinkert** [comment]
ok, should be fixed now. I must have not published the tag. sorry for the confusion.
