### ISSUE TITLE
gray-matter seems to be broken in Next 13

### ISSUE THREAD

**Issue by AnanyaGB** [jonschlinkert/gray-matter#162]
Hi, I've been trying to use `gray-matter` in Next 13, but just can't seem to make it work. It worked fine in the previous versions of Next.js, like Next 12. Could someone help me by giving a possible solution to this. Thanks

**Comment by nramkissoon** [comment]
Are you using YAML syntax? I managed to get it working server-side by switching to JS object syntax like this
```
---
{
title: "foo",
description: "bar"
}
---
```

**Comment by angblab** [comment]
@nramkissoon Thanks a lot man! You made my day. I was stuck in this for hours, ultimately had to put the entire meta-reading on standby. Thanks again.
