### ISSUE TITLE
README documentation for matter function doesn't indent options correctly

### ISSUE THREAD

**Issue by Ajedi32** [jonschlinkert/gray-matter#17]
At https://github.com/jonschlinkert/gray-matter#matter, the way the parameters are indented implies that delims and parser are seperate arguments, not part of the `options` object:

> **Params**
> - `string` **{String}**: The string to parse.
> - `options` **{Object}**
> - `delims` **{Array}**: Custom delimiters formatted as an array. The default is `['---', '---']`.
> - `parser` **{Function}**: Parser function to use. [js-yaml](https://github.com/nodeca/js-yaml)is the default.
> - `returns` **{Object}**: Valid JSON

This confused me for a bit until I looked at the source code.

**Comment by jonschlinkert** [comment]
that was a verb formatting issue that (I think) was fixed. noted, and thank you!

**Comment by jonschlinkert** [comment]
closing since this refers to an old version of gray-matter
