### ISSUE TITLE
Read folder with JSON-Files

### ISSUE THREAD

**Issue by jannikegger** [jonschlinkert/gray-matter#22]
Hey hey,

I'm currently setting up a project with metalsmith and gray-matter.
I try to store all my contents inside of one folder - saved as JSON-File. 
Is there a way to read all Files from one folder and access it inside my YAML definition?

To be more clear I have this example:

```
// Folder structure:
- dataContent
  - navigationEntries.json
  - stageContent.json
```

In one of my Template-Files I would like to use it like this (more or less)

```
// Maybe like this as I know it from assemble

---
title: A neat title
navEntries: <%= navigationEntries %>

---

<h1>
    {{ title }}
</h1>
{{#each navEntries}}
    {{> navPartial}}
{{/each}}
```

```
// Or maybe we can access the files directly without file extension?

---
title: A neat title

---
<h1>
    {{ title }}
</h1>
{{#each navigationEntries}}
    {{> navPartial}}
{{/each}}
```

Would be awesome if someone could help me :)
Thank you :)

**Comment by doowb** [comment]
`gray-matter` is used for extracting and parsing the front-matter from a string or file. Other libraries handle merging/extending data from the external `.json` files to produce the correct context. This is something that `assemble` does. I don't know how this would be achieved with `metalsmith`, but a simple example using the `dev` branch of `assemble` would look like this...

```sh
$ npm i assemble/assemble#dev
```

> build.js

```js
// create an instance of assemble
var assemble = require('assemble')();

// load the data files
assemble.data('dataContent/*.json');

// load layouts and partials
assemble.layouts('templates/layouts/*.hbs');
assemble.partials(templates/partials/*.hbs');

// load, render, write the pages
assemble.src('templates/pages/*.hbs')
  .pipe(assemble.renderFile())
  .pipe(assemble.dest('dist'));
```

```sh
$ node build.js
```

This will let you use the `navigationEntires` object in the `{{#each}}` statement like your second example.

**Comment by jonschlinkert** [comment]
closing since this is out of scope for this library
