### ISSUE TITLE
Archie Markup Language

### ISSUE THREAD

**Issue by RobLoach** [jonschlinkert/gray-matter#23]
[ArchieML](http://archieml.org/) is another markup language that could be used for front-matter:
https://www.npmjs.com/package/archieml

**Comment by jonschlinkert** [comment]
looks nice, thanks! should I consider this a feature request? or did you want to do a pr?

**Comment by jonschlinkert** [comment]
closing, languages can be added [via options](https://github.com/jonschlinkert/gray-matter#optionsengines)
