### ISSUE TITLE
TOML situation is unclear

### ISSUE THREAD

**Issue by marcoms** [jonschlinkert/gray-matter#25]
The readme and description imply that, though YAML is parsed by default, other languages (in this case only TOML is relevant) are supported by adding the language name after the `---`, e.g. `---toml\n`.

However, I've found that `toml` is only included in `devDependencies` not in `dependencies`, and since the `require("toml")` call in [lib/parsers.js#186](https://github.com/jonschlinkert/gray-matter/blob/master/lib/parsers.js#L186) fails silently if the `opts.strict` mode is off (undocumented), the user only gets an empty object as a return value. They wouldn't know that all they needed to do was to install `toml` locally to get it working.

I'm not sure whether `toml` support is supposed to be built in to the library, or if it is mean as an "optional extra"  to be installed it manually if the user wants TOML support, so I was just wondering what the "official" position was on this?

**Comment by jonschlinkert** [comment]
Sorry about any confusion. TOML is intentionally not built-in, and I think it should throw to let you know.  Seems like the `strict` option should have been removed when I refactored. I'll get this fixed next time I make changes.

**Comment by marcoms** [comment]
Thanks for the quick response. I made a [PR](https://github.com/jonschlinkert/gray-matter/pull/26) amending the readme to show how to enable support for by-default-disabled languages - is the wording OK?

**Comment by behnoodk** [comment]
This really is confusing. I'm not sure why #26 is still open after all this time. 
gray-matter still silently fails to parse TOML and there is no indication that the toml package should be installed separately.
Please clarify this in the docs.
Thank you

**Comment by jonschlinkert** [comment]
closing since this lib was refactored
