### ISSUE TITLE
fails to read front matter with duplicate keys

### ISSUE THREAD

**Issue by fitnr** [jonschlinkert/gray-matter#28]
Given a file like this (`test.html`):
```
---
id: 1
foo: bar
foo: baz
---
````
````js
> require('gray-matter').read('test.html')
{ orig: '---\nid: 1\nfoo: bar\nfoo: baz\n---',
  data: {},
  content: '',
  path: 'test.html' }
````

The data is completely empty because one key repeats. I would expect `gray-matter` to use the latest value in the front matter, or perhaps to throw an error.

**Comment by jonschlinkert** [comment]
Try setting `options.strict` to true, if that doesn't work we either need to improve error handling, or the issue is with js-yaml.

**Comment by fitnr** [comment]
Running with `{strict: true}` throws a `YAMLException` (duplicated mapping key). Thanks for the quick response.

**Comment by jonschlinkert** [comment]
no problem, thanks for using it

**Comment by jonschlinkert** [comment]
lol habit
