### ISSUE TITLE
Extra `\n` added when `stringify`-ing

### ISSUE THREAD

**Issue by EvanLovely** [jonschlinkert/gray-matter#29]
When I read a yaml file, then alter it, then re-stringify it so I can write it back, an extra `\n` gets added to the content. Check out [this example](https://tonicdev.com/evanlovely/57b215fbfff2dc1200399862/branches/master).

**Comment by jonschlinkert** [comment]
closing since gray-matter was refactored. I believe this was resolved. If you are still having an issue, please reopen, and a pr would be welcome.
