### ISSUE TITLE
matter.stringify() to accept output format

### ISSUE THREAD

**Issue by gmarty** [jonschlinkert/gray-matter#33]
Although gray-matter can parse many different types of format, `matter.stringify()` can only generate yaml front matters.
That'd be nice to be able to output all the formats supported (`json` is an obvious example of easy one to add support for).

**Comment by shaunakv1-noaa** [comment]
+1

**Comment by tech4him1** [comment]
@jonschlinkert Are you still planning on supporting this, and if so, is there anything I can do to help?

**Comment by zachwhaley** [comment]
@tech4him1 @jonschlinkert I added this to my fork for the time being.  Not sure if it would meet your needs, but I figured I should make it known :slightly_smiling_face: 

https://github.com/zachwhaley/gray-matter/commit/0fefe6943ae2522c4d3e4671ed165626b5485bee

**Comment by tech4him1** [comment]
@zachwhaley My bad, this is actually working as of v3.0.0. @gmarty I believe this issue can be closed.
