### ISSUE TITLE
Emit on parse error

### ISSUE THREAD

**Issue by ArmorDarks** [jonschlinkert/gray-matter#37]
So far if Gray Matter encounters Matter block, but unable to parse it (let's say, due to wrong escaping), it silently ignores it and outputs empty file.

It would be much better if Gray Matter instead emitted some event, so we can hook on it and log warning about invalid syntax, etc.

**Comment by jonschlinkert** [comment]
I agree, we need to completely refactor how the parsers work. I'll try to spend some time on this as soon as I have a chance

**Comment by ArmorDarks** [comment]
Well, for YAML `js-yaml` already [should throw](https://github.com/nodeca/js-yaml#safeload-string---options-) an error if it encounters syntax error. However, `gray-matter` seems to swallowing that error somewhere.

If it could be passed as a callback `(error) => do something with me`, it would solve the issue.

Another way would be a simple option like `opts.throwOnParseError`, which will force exception in case of parsing error.

**Comment by jonschlinkert** [comment]
this was [resolved in 3.0](https://github.com/jonschlinkert/gray-matter/blob/master/lib/engines.js#L17)

**Comment by ArmorDarks** [comment]
Wow, cool! I've totally missed new release. Thanks a lot!
