### ISSUE TITLE
Add dumper option to stringify to define a custom dumper.

### ISSUE THREAD

**Issue by zachwhaley** [jonschlinkert/gray-matter#39]
Similar to how you can define a parser to parse the yaml front-matter, I'd like to be able to define a dumper as well to dump the yaml front-matter.

**Comment by jonschlinkert** [comment]
this is planned for the next version. thanks

**Comment by zachwhaley** [comment]
Missed the open issue :stuck_out_tongue: 

Dupliate of #33

**Comment by jonschlinkert** [comment]
thanks, forgot about that!
