### ISSUE TITLE
Option to disable cache?

### ISSUE THREAD

**Issue by Leland-Kwong** [jonschlinkert/gray-matter#43]
I ran into an issue where I was mutating the output in a loop expecting the object to be brand new on each invocation.

```javascript
const frontMatter = require('gray-matter');

const docs = [
  {
    id: 1,
    content: ''
  },
  {
    id: 2,
    content: ''
  }
];

const parsedDocs = docs.map(doc => {
  const output = frontMatter(doc.content);
  Object.assign(output, { id: doc.id });
  return output;
}).map(({ id }) => id);

console.log(parsedDocs); // [2, 2] <-- expecting this to be [1, 2]
```

**Comment by doowb** [comment]
@Leland-Kwong will you update your example so it shows what's really happening and what you're expecting? Currently, `doc` and `doc2` aren't being used and `docs` isn't defined.

I don't want to make any assumptions about the example so we can try to figure it out.

**Comment by Leland-Kwong** [comment]
Ah, sorry about that, fixed it.

**Comment by doowb** [comment]
Thanks, that makes more sense, but when I run that I get `[1, 2]`.

`gray-matter` expects a string with front-matter like this:

```markdown
---
foo: bar
---
something here
```

 and returns an object that looks like this:

```js
{
  data: {foo: 'bar'},
  content: 'something here'
}
```

It's caching internally on the string passed in, so if you modify the string the front-matter should be re-parsed. Your example is passing in empty strings which will return an object like this:

```js
{
  data: {},
  content: ''
}
```

I'm assuming that your `doc.content` properties are supposed to have something in them, but I don't know what that is.

**Comment by Leland-Kwong** [comment]
Ah, ok, that makes sense now, my example was an extreme edge case. I had made a bunch of test files that had the exact same content, so it was returning the cached result on each call. I'll just go ahead and close this. Thanks!

**Comment by doowb** [comment]
@Leland-Kwong actually, after your last comment, I changed the example a little and I can reproduce the issue. I'm going to re-open since I think some of the logic needs to be updated.

**Updated example**
```js
const frontMatter = require('gray-matter');

const docs = [
  {
    id: 1,
    content: '---\nid: 2\n---\ndoc 2\n'
  },
  {
    id: 2,
    content: '---\nid: 2\n---\ndoc 2\n'
  }
];

const parsedDocs = docs.map(doc => {
  const output = frontMatter(doc);
  Object.assign(output, { id: doc.id });
  return output;
}).map(({ id }) => id);

console.log(parsedDocs); // [2, 2] <-- expecting this to be [1, 2]
```

For now, there's a work around. The caching only happens if the `options` argument is not passed in, so you can do `frontMatter(doc, {})`.

**Comment by Leland-Kwong** [comment]
Thanks @doowb. For the time being, I'm just doing `Object.assign({}, frontMatter(doc))` just to be extra safe.
