### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by caesar** [jonschlinkert/gray-matter#44]
It's hard to find the 'releases' section buried near the end of the huge Readme. (No complaint about the huge readme; that's great!)

Best practice is to keep a dedicated CHANGELOG.md file. This makes it easy to find out what breaking changes are in a new major release (for example).

See http://keepachangelog.com/ for more info.

**Comment by caesar** [comment]
Also, presumably "v3.0.0 - June 30, 2007" should be "2017"… ;-)

**Comment by jonschlinkert** [comment]
Want to do a PR?

**Comment by caesar** [comment]
Alright, I'll try and make time in the next few days...
