### ISSUE TITLE
Update CoffeeScript package path

### ISSUE THREAD

**Issue by lojaya** [jonschlinkert/gray-matter#55]
CoffeeScript has moved to https://www.npmjs.com/package/coffeescript

This changes affect vue-cli, please do change the package devDependencies from coffee-script to coffeescript

**Comment by aljopro** [comment]
If you are looking for an interum fix. add coffeescript 1.12.7 as a dev dependency of your package.json 

e.g.
`npm install coffee-script@1.12.7 --save-dev --save-exact`

**Comment by doowb** [comment]
Thanks for the issue. As pointed out in the `vue-cli` issues, they are using `gray-matter` through `metalsmith` which uses an older version of `gray-matter`. Newer versions of `gray-matter` specify `coffee-script` in `devDependencies` which would mean that it does not get installed when `gray-matter` is used as a dependency.

Also, it seems that `coffee-script` fixed their end by tagging `1.12.7` as the `latest`.
`vue-cli` also pinned the `coffee-script` version so `vue-cli` should be working now.

Thanks @aljopro for the update. This should only be necessary now if you're using an old version of `gray-matter` directly.
