### ISSUE TITLE
Not all emojis are parsed

### ISSUE THREAD

**Issue by hilja** [jonschlinkert/gray-matter#60]
When stringifying I see emoji codepoints and not the characters, but weirdly some emojis work.

I made this runkit where the behaviour can be tested https://runkit.com/embed/d0vr3nxedg9u.

```
const grayMatter = require("gray-matter")
const emojis = [ '😂', '😒', '😔', '✌️', '😭', '👌', '😑', '😞', '😏', '😢' ]
grayMatter.stringify('Foo', { emojis })
```

Results in:

```
---
emojis:
  - "\uD83D\uDE02"
  - "\uD83D\uDE12"
  - "\uD83D\uDE14"
  - ✌️
  - "\uD83D\uDE2D"
  - "\uD83D\uDC4C"
  - "\uD83D\uDE11"
  - "\uD83D\uDE1E"
  - "\uD83D\uDE0F"
  - "\uD83D\uDE22"
---
Foo
```

**Comment by jonschlinkert** [comment]
Does this belong here? Seems like a bug with the yaml processor.

**Comment by hilja** [comment]
Okay, I had an old gray-matter version, it's fixed https://github.com/nodeca/js-yaml/pull/369. But they still use the unicode sequence `\U0001F600` rather than the actual emoji, not human readable. But anyway, it works like this.

**Comment by unrevised6419** [comment]
I did also encounter some of the emojis that are saved as a unicode sequence.
Is something I can do to fix it?

| Source | Destination |
|--------|--------|
| `"🪆 Nesting and ..."` | `"\U0001FA86 Nesting and ..."` |
| `"♻️ Override DOM ..."` | `♻️ Override DOM ...` |
| `"🗄️ Create own ..."` | `"\U0001F5C4️ Create own ..."` |

**Comment by unrevised6419** [comment]
Installed `js-yaml@4` and override the `engines.yaml` with this, and it seems to work fine now.

> [!NOTE]
> `js-yaml@4` has breaking changes, they renamed the methods
> — https://github.com/nodeca/js-yaml/blob/master/migrate_v3_to_v4.md

```ts
const content = gray.stringify(matter.content, matterData, {
	engines: {
		yaml: {
			parse: (input) => yaml.load(input),
			stringify: (input) => yaml.dump(input),
		},
	},
});
```
