### ISSUE TITLE
Is the repository still maintained?

### ISSUE THREAD

**Issue by barraq** [jonschlinkert/gray-matter#61]
Hi all!

is this repository still maintained? There are a few open [pull requests](https://github.com/jonschlinkert/gray-matter/pulls), including [mine](https://github.com/jonschlinkert/gray-matter/pull/54), that have been open for a few months. I would be happy to help if support is needed: I would need some additional permissions however.

@jonschlinkert, @doowb

**Comment by jonschlinkert** [comment]
Yes
