### ISSUE TITLE
optional descriptive field

### ISSUE THREAD

**Issue by mofosyne** [jonschlinkert/gray-matter#7]
Just one suggestion. Can you allow for optional descriptive field after the 'language specifier'? This is most useful, for repeated metadata within the documents. E.g. Slideshow apps might need to set different stylesheet for each slides, so need to be able to distinguish between different metadata boxes.

```
---yaml: slide01 ---
CSS: style.css

---
```

Originally from: [Metadata in documents](http://talk.commonmark.org/t/metadata-in-documents/721/66?u=mofosyne)

Related discussion: [Jekyll style “do not show or parse”](http://talk.commonmark.org/t/jekyll-style-do-not-show-or-parse-sections/918)

**Comment by jonschlinkert** [comment]
HI, thanks for the suggestion but we won't be adding support for non-standard features.
