### ISSUE TITLE
Question: Where should I add add link to the webpack loader created for this project

### ISSUE THREAD

**Issue by ajaymathur** [jonschlinkert/gray-matter#81]
Hi, Love the library by the way ❤️

We needed to achieve this but wanted to do extract the gray matter from the docs at the build time. Therefore, we have created a webpack loader for gray-matter( https://github.com/atlassian/gray-matter-loader ).

I am looking forward to add the link to the project in readme of this project so that someone with a use case can find it easily.

I see **Related projects** as the most relevant section. What are the thoughts on this?

**Comment by tunnckoCore** [comment]
Yea, me too.

**Comment by robertmassaioli** [comment]
Thanks for the docs update!
