### ISSUE TITLE
Invalid TypeScript type definition for `engines` option

### ISSUE THREAD

**Issue by caesar** [jonschlinkert/gray-matter#83]
The TypeScript type definition is invalid due to missing types on the parameters for the `engines` callbacks.

When running TypeScript with the `noImplicitAny` option, the following error is emitted three times:
`Parameter has a name but no type. Did you mean 'arg0: string'?`

The incorrect definition is in the following lines (the two `string`s and the `object` are being interpreted as parameter names rather than types because no names are given).

https://github.com/jonschlinkert/gray-matter/blob/97eb641a0b42d80ce752973ab4a1bdf0c76d875c/gray-matter.d.ts#L31-L35

If I can work out what the syntax is for the `engines` callbacks I'll submit a PR.

**Comment by caesar** [comment]
Ah – I see there are already two open PRs identical to mine (dating back as far as April…).
My mistake; I checked for similar issues but not PRs.

See #74 and #77.

**Comment by robertmassaioli** [comment]
This has been fixed and released in `4.0.2`.
