### ISSUE TITLE
Handling of "---" within values

### ISSUE THREAD

**Issue by davidsinclair** [jonschlinkert/gray-matter#9]
Hi,

Values containing '---' do not seem to be handled correctly. For example the following is valid yaml (the value of name is quoted and so the -- should not be treated as the start of the markdown block).

<pre>
- name: "troublesome --- value"
---
here is some content
</pre>

We ran across this because we want to have more than one block of markdown.

Thanks,

David

**Comment by jonschlinkert** [comment]
Let me know if you have any more issues. thanks for reporting.
